/**
 * build-brain.mjs
 *
 * Reads all brain markdown files and writes them to src/data/brain.ts
 * so the Next.js app can render them at runtime.
 *
 * Run: node scripts/build-brain.mjs
 * Auto-runs before every build via package.json prebuild script.
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'fs'
import { join, relative, basename } from 'path'

const BRAIN_DIR = join(import.meta.dirname, '..', 'brain')
const OUTPUT = join(import.meta.dirname, '..', 'src', 'data', 'brain.ts')

// Map brain file paths to project slugs
const SLUG_MAP = {
  'state.md': '_state',
  'jeff.md': 'jeff',
  'ffeedd.md': 'ffeedd',
  'madder.md': 'madder',
  'dream-beds.md': 'dream-beds',
  'life-admin.md': 'life-admin',
  'tango/overview.md': 'tango',
  'tango/amazon.md': 'tango-amazon',
  'tango/costco.md': 'tango-costco',
  'tango/dtc.md': 'tango-dtc',
  'tango/unfi.md': 'tango-unfi',
  'tango/production.md': 'tango-production',
  'tango/notion-dump.md': 'tango-notion-dump',
}

// Extract a <100 char summary from the "Current Understanding" section
function extractSummary(content) {
  // Find "## Current Understanding" section
  const match = content.match(/##\s*(?:My )?Current Understanding\s*\n+([\s\S]*?)(?=\n##|\n$|$)/)
  if (!match) return ''

  // Get first sentence(s) of the section, strip markdown formatting
  const text = match[1]
    .replace(/\*\*/g, '')           // remove bold
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // links to text
    .replace(/[#*_`]/g, '')         // other markdown chars
    .replace(/\n+/g, ' ')          // newlines to spaces
    .trim()

  // Take up to 100 chars, break at last word boundary
  if (text.length <= 100) return text
  const truncated = text.slice(0, 100)
  const lastSpace = truncated.lastIndexOf(' ')
  return (lastSpace > 60 ? truncated.slice(0, lastSpace) : truncated) + '…'
}

function discoverBrainFiles(dir, base = '') {
  const entries = []
  for (const item of readdirSync(dir)) {
    const full = join(dir, item)
    const rel = base ? `${base}/${item}` : item
    if (statSync(full).isDirectory()) {
      entries.push(...discoverBrainFiles(full, rel))
    } else if (item.endsWith('.md')) {
      entries.push(rel)
    }
  }
  return entries
}

// Discover all .md files
const files = discoverBrainFiles(BRAIN_DIR)

// Build the data
const brainEntries = []

for (const relPath of files) {
  const slug = SLUG_MAP[relPath]
  if (!slug) {
    // Unknown file — derive slug from filename
    const name = basename(relPath, '.md')
    console.warn(`[build-brain] No slug mapping for ${relPath}, skipping`)
    continue
  }

  const content = readFileSync(join(BRAIN_DIR, relPath), 'utf-8')
  brainEntries.push({ slug, relPath, content })
}

// Sort: state first, then alphabetical
brainEntries.sort((a, b) => {
  if (a.slug === '_state') return -1
  if (b.slug === '_state') return 1
  return a.slug.localeCompare(b.slug)
})

// Generate TypeScript
const ts = `// AUTO-GENERATED by scripts/build-brain.mjs — do not edit manually
// Last built: ${new Date().toISOString()}

export interface BrainFile {
  slug: string
  path: string
  content: string
  summary: string
  updatedAt: string
}

export const BRAIN_FILES: BrainFile[] = ${JSON.stringify(
  brainEntries.map(e => ({
    slug: e.slug,
    path: e.relPath,
    content: e.content,
    summary: extractSummary(e.content),
    updatedAt: new Date().toISOString(),
  })),
  null,
  2
)}

export function getBrainFile(slug: string): BrainFile | undefined {
  return BRAIN_FILES.find(b => b.slug === slug)
}

export function getAllBrainFiles(): BrainFile[] {
  return BRAIN_FILES
}
`

writeFileSync(OUTPUT, ts, 'utf-8')
console.log(`[build-brain] Wrote ${brainEntries.length} brain files to src/data/brain.ts`)
for (const e of brainEntries) {
  console.log(`  ${e.slug} ← ${e.relPath} (${e.content.length} chars)`)
}
